# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abid Butt
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A creative and dynamic leader with a passion for tourism and hospitality.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abid-butt.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
  features:
    output: true
    permalink: /:path
